parameters: {}
environment: {}
packages:
    - name: waiting
      shared: false
      functions:
        - name: room
          binary: false
          main: "waiting-room.py"
          runtime: python:3.11
          web: "raw"
          webSecure: false
          limits: {}
