parameters: {}
packages:
  - name: khisdapaze
    shared: false
    parameters: {}
    annotations: {}
    functions:
      - name: waiting-room
        binary: false
        main: "waiting-room.py"
        runtime: python:3.11
        web: "raw"
        parameters: {}
        annotations: {}
        limits: {}