parameters: {}
environment: {}
packages:
    - name: pretix
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: waitingroom
          binary: false
          main: ""
          runtime: python:3.11
          web: "raw"
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
