parameters: {}
packages:
    - name: default
      shared: false
      parameters: {}
      annotations: {}
      functions:
        - name: "waiting-room"
          binary: false
          main: ""
          runtime: python:3.11
          web: "raw"
          environment:
            REDIS_LOCATION: ${REDIS_LOCATION}
            WAITING_ROOM_SECRET: ${WAITING_ROOM_SECRET}
            WAITING_ROOM_MAX_USERS: "${WAITING_ROOM_MAX_USERS}"
          parameters: {}
          annotations: {}
          limits: {}
