parameters: {}
packages:
    - name: default
      shared: false
      parameters: {}
      annotations: {}
      functions:
        - name: "waiting-room"
          binary: false
          main: ""
          runtime: python:3.11
          web: "raw"
          parameters: {}
          annotations: {}
          limits: {}
