parameters: {}
packages:
  - name: waiting
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: room
        binary: false
        main: "waiting-room.py"
        runtime: python:3.11
        web: "raw"
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}