[project]
name = "pretix-waitingroom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black[d]>=25.1.0",
    "redis>=6.4.0",
    "requests>=2.32.5",
]
